sonar.organization=metratio
sonar.projectKey=metratio_semantic-language
sonar.projectName=semantic-language
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
