sonar.organization=metratio
sonar.projectKey=metratio_autonomous-development
sonar.projectName=autonomous-development
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
