ADMINISTRATIVE_HRIS_EMPLOYEE_CREATE = "administrative.hris.employee.create.v1"
ADMINISTRATIVE_HRIS_EMPLOYEE_DEACTIVATE = "administrative.hris.employee.deactivate.v1"
ADMINISTRATIVE_IAM_IDENTITY_CREATE = "administrative.iam.identity.create.v1"
ADMINISTRATIVE_IAM_IDENTITY_DISABLE = "administrative.iam.identity.disable.v1"
ADMINISTRATIVE_IAM_SESSIONS_REVOKE = "administrative.iam.sessions.revoke.v1"
ADMINISTRATIVE_COMMUNICATION_MESSAGE_SEND = "administrative.communication.message.send.v1"
ADMINISTRATIVE_ERP_PURCHASE_ORDER_CREATE_DRAFT = (
    "administrative.erp.purchase-order.create-draft.v1"
)
ADMINISTRATIVE_ERP_PURCHASE_ORDER_CONFIRM = "administrative.erp.purchase-order.confirm.v1"
ADMINISTRATIVE_ERP_VENDOR_BILL_CREATE_DRAFT = (
    "administrative.erp.vendor-bill.create-draft.v1"
)
ADMINISTRATIVE_ERP_EXPENSE_REPORT_CREATE = "administrative.erp.expense-report.create.v1"

WORLD_RUNTIME_EFFECT_CAPABILITIES = frozenset(
    {
        ADMINISTRATIVE_HRIS_EMPLOYEE_CREATE,
        ADMINISTRATIVE_HRIS_EMPLOYEE_DEACTIVATE,
        ADMINISTRATIVE_IAM_IDENTITY_CREATE,
        ADMINISTRATIVE_IAM_IDENTITY_DISABLE,
        ADMINISTRATIVE_IAM_SESSIONS_REVOKE,
        ADMINISTRATIVE_COMMUNICATION_MESSAGE_SEND,
        ADMINISTRATIVE_ERP_PURCHASE_ORDER_CREATE_DRAFT,
        ADMINISTRATIVE_ERP_PURCHASE_ORDER_CONFIRM,
        ADMINISTRATIVE_ERP_VENDOR_BILL_CREATE_DRAFT,
        ADMINISTRATIVE_ERP_EXPENSE_REPORT_CREATE,
    }
)
