sonar.organization=metratio
sonar.projectKey=metratio_administrative-orchestrator
sonar.projectName=administrative-orchestrator
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

